<?php
// $Id$

/**
 * @file
 * Handels tema sites panels plusings and additions.
 */

define('MODULENAME_MINIMUM_CTOOLS_API_VERSION', '1.3');
define('MODULENAME_MAXIMUM_CTOOLS_API_VERSION', '1.8');

/**
 * Ensures that ctools has the right API version.
 *
 */
function ding_panels_tema_requirements($phase) {
  $requirements = array();
  if (!module_invoke('ctools', 'api_version', MODULENAME_MINIMUM_CTOOLS_API_VERSION, MODULENAME_MAXIMUM_CTOOLS_API_VERSION)) {
    $requirements['MODULENAME_ctools'] = array(
      'title' => t('MODULENAME required Chaos Tool Suite (CTools) API Version'),
      'value' => t('Between @a and @b', array('@a' => MODULENAME_MINIMUM_CTOOLS_API_VERSION, '@b' => MODULENAME_MAXIMUM_CTOOLS_API_VERSION)),
      'severity' => REQUIREMENT_ERROR,
    );
  }
  return $requirements;
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ding_panels_tema_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function ding_panels_tema_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

function ding_panels_tema_theme($existing, $type, $theme, $path) {
  return array(
    'ding_panels_tema_content_header' => array(
      'arguments' => array('node' => NULL, 'conf' => NULL),
      'template' => 'templates/ding-panels-tema-header',
      'preprocess functions' => array('ding_panels_tema_preprocess_header'),
    ),
  );
}

function ding_panels_tema_preprocess_header(&$variables, $hook) {
  $node = $variables['node'];

  // Create title image
  if ($variables['conf']['display_header_image']) {
    $variables['titleimage'] = theme('imagecache', '680_200_crop', $node->field_tema_image[0]['filepath']);
  }

  // Set title
  $variables['title'] = l($node->title, 'node/' . $node->nid);
  
  // Load menu (using menu block)  
  $conf = array('menu_name' => 'tema-site-' . $node->nid,
                'parent_mlid' => 0, 'title_link' => 0,
                'admin_title' => 'Tema menu (0)',
                'level' => 0, 'follow' => 0, 'depth' => 1,
                'expanded' => 0, 'sort' => 0,
                'override_title' => 1, 'override_title_text' => '',
                'delta' => 'tema-menu' );
  $tree = menu_tree_build($conf);
  $variables['menu'] = $tree['content'];
}