<?php
/**
 * @file
 * Handles Panels plugins and additions for tema sites.
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function ding_panels_tema_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_theme().
 */
function ding_panels_tema_theme($existing, $type, $theme, $path) {
  return array(
    'ding_panels_tema_content_header' => array(
      'arguments' => array('node' => NULL, 'conf' => NULL),
      'template' => 'ding-panels-tema-header',
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Preprocess variables for ding-panels-tema-header.tpl.php
 */
function ding_panels_tema_preprocess_ding_panels_tema_content_header(&$variables, $hook) {
  $node = $variables['node'];

  // Create title image
  if ($variables['conf']['display_header_image']) {
    $variables['titleimage'] = theme('imagecache', '680_200_crop', $node->field_tema_image[0]['filepath']);
  }

  // Set title
  $variables['title'] = l($node->title, 'node/' . $node->nid);
  
  // Load menu (using menu block)  
  $conf = array('menu_name' => 'tema-site-' . $node->nid,
                'parent_mlid' => 0, 'title_link' => 0,
                'admin_title' => 'Tema menu (0)',
                'level' => 0, 'follow' => 0, 'depth' => 1,
                'expanded' => 0, 'sort' => 0,
                'override_title' => 1, 'override_title_text' => '',
                'delta' => 'tema-menu' );
  $tree = menu_tree_build($conf);
  $variables['menu'] = $tree['content'];
}

include_once('ding_panels_tema.features.inc');

